import React, { useState } from 'react';
import { Icons } from '../Icons';

export default function MetaAiArea() {
  const [inputValue, setInputValue] = useState('');
  const [showBanner, setShowBanner] = useState(true);

  const suggestions = [
    '/imagine a car race on mars',
    'What are the most popular shows on Netflix?',
    'Give me a recipe for banana bread'
  ];

  const handleSubmit = (e) => {
    e.preventDefault();
    if (!inputValue.trim()) return;
    setInputValue('');
  };

  return (
    <div className="main-area meta-ai-area" style={{ position: 'relative', overflow: 'hidden', display: 'flex', flexDirection: 'column', height: '100%' }}>
      {/* Background doodles */}
      <div style={{ position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundImage: 'url("https://static.whatsapp.net/rsrc.php/v3/yO/r/FsZus2B1B6t.png")', opacity: 0.04, pointerEvents: 'none' }}></div>
      
      <div className="active-chat-header" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', zIndex: 2, borderBottom: 'none' }}>
        <div className="active-chat-info" style={{ display: 'flex', alignItems: 'center', gap: '15px' }}>
          <div className="avatar avatar-icon" style={{ backgroundColor: 'transparent', width: '40px', height: '40px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <Icons.MetaAILogo />
          </div>
          <div>
            <div className="active-chat-name" style={{ display: 'flex', alignItems: 'center', gap: '6px', color: 'var(--text-primary)', fontSize: '16px', fontWeight: '400' }}>
              Meta AI 
              <svg viewBox="0 0 16 16" height="12" width="12" fill="var(--text-secondary)">
                <path d="M7.4 1.8l-1.3 3.6L2.5 6.7c-.4.2-.4.8 0 1l3.6 1.3 1.3 3.6c.2.4.8.4 1 0l1.3-3.6 3.6-1.3c.4-.2.4-.8 0-1L9.7 5.4 8.4 1.8c-.2-.4-.8-.4-1 0z" />
              </svg>
            </div>
          </div>
        </div>
        <div className="header-icons" style={{ display: 'flex', gap: '20px', color: 'var(--text-secondary)' }}>
          <div className="icon" style={{ cursor: 'pointer' }}><Icons.Search /></div>
          <div className="icon" style={{ cursor: 'pointer' }}><Icons.Menu /></div>
        </div>
      </div>

      {showBanner && (
        <div className="meta-ai-banner" style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px 24px', backgroundColor: '#182229', zIndex: 2 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
            <svg viewBox="0 0 24 24" height="20" width="20" fill="var(--text-secondary)">
              <path d="M19 19H5V5h7V3H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h14c1.1 0 2-.9 2-2v-7h-2v7zM14 3v2h3.59l-9.83 9.83 1.41 1.41L19 6.41V10h2V3h-7z"/>
            </svg>
            <span style={{ color: 'var(--text-secondary)', fontSize: '14.5px' }}>
              On Meta AI web you can organise your Meta AI chats by topic, create AI-powered docs and more. <span style={{ color: 'var(--accent-green)', cursor: 'pointer', fontWeight: '500' }}>Try it</span>
            </span>
          </div>
          <div className="icon" onClick={() => setShowBanner(false)} style={{ cursor: 'pointer', color: 'var(--text-secondary)' }}>
            <svg viewBox="0 0 24 24" height="20" width="20" fill="currentColor">
              <path d="M19 6.41L17.59 5 12 10.59 6.41 5 5 6.41 10.59 12 5 17.59 6.41 19 12 13.41 17.59 19 19 17.59 13.41 12z" />
            </svg>
          </div>
        </div>
      )}

      <div className="chat-history" style={{ display: 'flex', flexDirection: 'column', padding: '20px 5%', zIndex: 1, flex: 1, overflowY: 'auto', backgroundColor: 'transparent' }}>
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '20px', marginTop: 'auto' }}>
          <span style={{ backgroundColor: 'var(--bg-panel-hover)', color: 'var(--text-secondary)', fontSize: '12.5px', padding: '6px 12px', borderRadius: '8px' }}>Today</span>
        </div>
        
        <div style={{ display: 'flex', justifyContent: 'center', marginBottom: '40px' }}>
          <div style={{ backgroundColor: 'var(--bg-panel-hover)', color: 'var(--text-secondary)', fontSize: '13.5px', padding: '12px 16px', borderRadius: '8px', maxWidth: '420px', textAlign: 'center', lineHeight: '1.5' }}>
            Messages are generated by AI from Meta. Some may be inaccurate or inappropriate. You can improve the quality by sending feedback. Click to learn more.
          </div>
        </div>

        <div style={{ display: 'flex', gap: '12px', overflowX: 'auto', paddingBottom: '16px', justifyContent: 'flex-start', flexWrap: 'wrap' }}>
          {suggestions.map((suggestion, index) => (
            <button 
              key={index}
              style={{ backgroundColor: 'var(--bg-panel-hover)', color: 'var(--text-primary)', border: 'none', borderRadius: '20px', padding: '10px 16px', fontSize: '14.5px', cursor: 'pointer' }}
              onClick={() => setInputValue(suggestion)}
            >
              {suggestion}
            </button>
          ))}
        </div>
      </div>

      <form className="message-input-area" onSubmit={handleSubmit} style={{ backgroundColor: 'transparent', padding: '10px 5%', zIndex: 1, display: 'flex', alignItems: 'center', marginBottom: '10px' }}>
        <div style={{ flex: 1, backgroundColor: 'var(--search-bg)', borderRadius: '24px', display: 'flex', alignItems: 'center', padding: '12px 20px', gap: '16px' }}>
          <div style={{ display: 'flex', gap: '16px', color: 'var(--text-secondary)' }}>
            <button type="button" style={{ background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', padding: 0, display: 'flex' }}><Icons.Plus /></button>
            <button type="button" style={{ background: 'none', border: 'none', color: 'inherit', cursor: 'pointer', padding: 0, display: 'flex' }}><Icons.Smile /></button>
          </div>
          
          <input 
            type="text" 
            placeholder="Type a message" 
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            style={{ backgroundColor: 'transparent', border: 'none', color: 'var(--text-primary)', width: '100%', fontSize: '15px', outline: 'none' }}
          />
          
          {inputValue.trim() ? (
            <button type="submit" style={{ background: 'none', border: 'none', color: 'var(--accent-green)', cursor: 'pointer', padding: 0, display: 'flex' }}><Icons.NewChat /></button>
          ) : (
            <button type="button" style={{ background: 'none', border: 'none', color: 'var(--text-secondary)', cursor: 'pointer', padding: 0, display: 'flex' }}><Icons.Mic /></button>
          )}
        </div>
      </form>
    </div>
  );
}
