import React, { useState } from 'react';
import './index.css';
import NavSidebar from './components/NavSidebar';
import ChatSidebar from './components/ChatSidebar';
import ChatArea from './components/ChatArea';
import StatusSidebar from './components/StatusSidebar';
import StatusArea from './components/StatusArea';
import ChannelsSidebar from './components/ChannelsSidebar';
import ChannelsArea from './components/ChannelsArea';
import CommunitiesSidebar from './components/CommunitiesSidebar';
import CommunitiesArea from './components/CommunitiesArea';
import MetaAiArea from './components/MetaAiArea';
import { initialContacts, initialMessages } from './data';

function App() {
  const [activeChat, setActiveChat] = useState(null); // Default to no chat to show welcome screen
  const [messages, setMessages] = useState(initialMessages);
  const [currentView, setCurrentView] = useState('chat'); // 'chat' or 'status'

  const handleSendMessage = (text) => {
    if (!activeChat) return;

    const newMsg = {
      id: Date.now(),
      sender: 'me',
      text: text,
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setMessages({
      ...messages,
      [activeChat.id]: [...(messages[activeChat.id] || []), newMsg]
    });
  };

  return (
    <div className="app-container">
      <NavSidebar currentView={currentView} onViewChange={setCurrentView} />
      
      {currentView === 'chat' && (
        <>
          <ChatSidebar 
            contacts={initialContacts} 
            activeChat={activeChat} 
            onSelectChat={setActiveChat} 
          />
          <ChatArea 
            activeChat={activeChat} 
            messages={messages} 
            onSendMessage={handleSendMessage} 
          />
        </>
      )}

      {currentView === 'status' && (
        <>
          <StatusSidebar />
          <StatusArea />
        </>
      )}

      {currentView === 'channels' && (
        <>
          <ChannelsSidebar 
            activeChat={activeChat} 
            onSelectChat={setActiveChat} 
          />
          {activeChat && activeChat.isChannel ? (
            <ChatArea 
              activeChat={activeChat} 
              messages={messages} 
              onSendMessage={handleSendMessage} 
            />
          ) : (
            <ChannelsArea />
          )}
        </>
      )}

      {currentView === 'communities' && (
        <>
          <CommunitiesSidebar 
            activeChat={activeChat} 
            onSelectChat={setActiveChat} 
          />
          {activeChat && activeChat.isCommunity ? (
            <ChatArea 
              activeChat={activeChat} 
              messages={messages} 
              onSendMessage={handleSendMessage} 
            />
          ) : (
            <CommunitiesArea />
          )}
        </>
      )}

      {currentView === 'meta-ai' && (
        <>
          <ChatSidebar 
            contacts={[
              {
                id: 'meta-ai',
                name: 'Meta AI',
                time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
                lastMessage: 'Messages are generated by AI from Meta. Some may be ina...',
                isMetaAi: true,
                unread: 0
              },
              ...initialContacts
            ]} 
            activeChat={{ id: 'meta-ai', name: 'Meta AI', isMetaAi: true }} 
            onSelectChat={() => {}} 
          />
          <MetaAiArea />
        </>
      )}
    </div>
  );
}

export default App;